### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by Wajdimassoudi** [Wajdimassoudi/312564#2]
`style.css`

```css
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
}

nav ul {
    list-style-type: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin: 0 15px;
}

nav a {
    color: white;
    text-decoration: none;
}

section {
    padding: 20px;
}

.property-list, .car-list {
    display: flex;
    flex-wrap: wrap;
}

.property, .car {
    border: 1px solid #ccc;
    padding: 10px;
    margin: 10px;
    width: 200px;
}

footer {
    background-color: #4CAF50;
    color: white;
    text-align: center;
    padding: 10px 0;
}
````
